#:kivy 1.7.2

PageLayout:
    Button:
        id: bswitch

    GridLayout:
        columns: 2
        #orientation: 'vertical' if bswitch.state == 'down' else 'horizontal'

        Button:
            id: btn1
            column: 1
            text: 'Button 1'

##        Button:
##            column: 2
##            text: btn1.state
##
##        Button:
##            text: 'Button 3'
##
##        Button:
##            text: 'Button 4'
##
##        Button:
##            text: 'Button 5'

