<cieBackground>:
    canvas:
        Color:
            rgba: 0,0,0,1
        Rectangle:
            size: 500, 500
    Image:
        source: 'cie_xyz_clear.png'
        size: 870/2,972/2
##        on_touch_down: root.on_touch_down()

<HueLayout>:
    colorloopwidget: colorloopwidget
    xlabel: xlabel
    ylabel: ylabel
    
    BoxLayout:
        size: 1000, 500
        orientation: 'horizontal'
        FloatLayout:
            ColorLoopWidget:
                xlabel: xlabel
                ylabel: ylabel
                id: colorloopwidget
                size: 500, 500
            cieBackground:

        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Clear'
                on_release: root.clear_canvas()
            Label:
                id: xlabel
                text: 'x: '
                size_hint_y: 0.2
            Label:
                id: ylabel
                text: 'y: '
                size_hint_y: 0.2
